const actiontypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',

    LOGIN_SUCCESS:      'LOGIN_SUCCESS',
    LOGIN_FAILED:       'LOGIN_FAILED',

    LOGOUT_SUCCESS:     'LOGOUT_SUCCESS',

    GET_PROFILE_SUCCESS:    'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILED:     'GET_PROFILE_FAILED',

    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILED:  'UPDATE_PROFILE_FAILED'
}

export default actiontypes